#
# Copyright 2021-2022 Micro Focus or one of its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
{{ if .Values.global.rbac.serviceAccountCreate -}}
  {{- range $tenant := $.Values.deployment.tenants }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $tenant.id }}-{{ $.Values.deployment.rbac.serviceAccountSuffix }}
  namespace: {{ $.Release.Namespace }}
imagePullSecrets:
- name: {{ $.Values.global.docker.imagePullSecret | default "registrypullsecret" }}
  {{- end }} {{- /* range $tenant := $.Values.deployment.tenants */}}
{{- end }} {{- /* if .Values.global.rbac.serviceAccountCreate */}}

{{- /* ============================================================================================================ */}}
{{- if .Values.global.rbac.roleCreate }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.deployment.rbac.clusterRoleName }}
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - list
  - watch
  - delete
{{- /* Still appears to be an issue: https://github.com/kubernetes/kubernetes/issues/67439 */}}
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - delete
- apiGroups:
  - {{ .Values.crd.group }}
  resources:
  - flinkjobs
  - flinkjobs/status
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: itom-flork-lease-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - '*'
{{- /* ============================================================================================================ */}}
  {{- range $tenant := $.Values.deployment.tenants }}
    {{- if has "*" $tenant.namespaces }}
      {{- if gt (len $.Values.deployment.tenants) 1 }}
        {{- fail "Only 1 tenant is allowed if all namespaces should be managed by a single tenant." }}
      {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $tenant.id }}-itom-flork-cluster-rb
subjects:
- kind: ServiceAccount
  name: {{ $tenant.id }}-{{ $.Values.deployment.rbac.serviceAccountSuffix }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.deployment.rbac.clusterRoleName }}

    {{- else }} {{- /* if has '*' $tenant.namespaces -------------------------------------------------------------- */}}
      {{- range $namespace := $tenant.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $tenant.id }}-{{ $namespace }}-itom-flork-rb
  namespace: {{ $namespace }}
subjects:
- kind: ServiceAccount
  name: {{ $tenant.id }}-{{ $.Values.deployment.rbac.serviceAccountSuffix }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.deployment.rbac.clusterRoleName }}

      {{- end }} {{- /* range $tenant.namespaces */}}
    {{- end }} {{- /* if/else has '*' $tenant.namespaces ---------------------------------------------------------- */}}
{{- /* ============================================================================================================ */}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $tenant.id }}-itom-flork-lease-rb
  namespace: {{ $.Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ $tenant.id }}-{{ $.Values.deployment.rbac.serviceAccountSuffix }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: itom-flork-lease-role
  {{- end }} {{- /* range $tenant := $.Values.deployment.tenants */}}
{{- end }} {{- /* if $.Values.global.rbac.roleCreate */}}
